### ISSUE TITLE
Реализовать добавление новых пользователей в систему

### ISSUE THREAD

**Issue by programmer-kazarin** [tlavida/pantao-st-crm#5]
Реализовать АПИ, которое на вход принимает ФИО и роль нового пользователя и сохраняет его в БД.
Если пользователь уже есть, возвращать 409 ошибку.

**Comment by programmer-kazarin** [comment]
Структура папок проекта:
* configuration 
* controllers
* service
* domain
    - entity
    - enums
* repo

**Comment by tlavida** [comment]
https://github.com/tlavida/pantao-st-crm/pull/10

**Comment by programmer-kazarin** [comment]
Покрыть тестами сервисы

**Comment by programmer-kazarin** [comment]
Исправить замечания из кодревью
